{{- if and .Values.prometheus.enabled .Values.prometheus.prometheusRule.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "mychart.fullname" . }}
spec:
  groups:
    - name: {{ include "mychart.fullname" . }}
      rules:
        {{- range .Values.prometheus.prometheusRule.rules }}
        - alert: {{ .alert }}
          expr: {{ .expr }}
          for: {{ .for }}
          labels:
            severity: {{ .labels.severity }}
          annotations:
            summary: {{ .annotations.summary }}
        {{- end }}
{{- end }}