apiVersion: v1
kind: Secret
metadata: 
    name: postgres-credentials
type: Opaque
data: 
    postgresql-database: dG9kb2xpc3Q=
    postgresql-password: ek02IypkaXRWbkVlRXE=
    postgresql-username: cG9zdGdyZXNxbA==



