replicaCount: 1
image:
  repository: todolist
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30001

ingress: 
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: todolist.local
      paths:
        - path: /
          pathType: Prefix

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: todolist

postgresql:
  enabled: true
  postgresqlUsername: todolist
  postgresqlPassword: todolist
  postgresqlDatabase: todolist
  persistence:
    enabled: true
    size: 1Gi