# name: Deploy to KinD
# on: [workflow_dispatch, push]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Install Helm
#       uses: azure/setup-helm@v1

#     - name: Create KinD cluster
#       uses: container-tools/kind-action@v2.0.3
    
#     - name: Build and push Docker image
#       run: |
#         docker build -t localhost:5000/todolist:latest ./.
#         docker push localhost:5000/todolist:latest

#     - name: Add prometheus-operator 
#       run: |
#         kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.50/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
#         kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-0.50/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml

#     - name: Deploy Postgres chart
#       run: |
#         helm repo add bitnami https://charts.bitnami.com/bitnami
#         helm install my-postgresql bitnami/postgresql --version 14.3.1 --set auth.database=todo

#     - name: Deploy Application
#       run: |
#         helm install todolist ./todolist/
